### ISSUE TITLE
Todo AZD template for AKS

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-dev#1616]
- [ ] AKS bicep
  - [ ] Simple ingress using [Web App Routing Add-on](https://learn.microsoft.com/en-us/azure/aks/web-app-routing?tabs=with-osm)
- [ ] Custom k8s manifest creation for k8s components (k8s manifests or kustomize)
  - [ ] Namespace
  - [ ] Deployments
  - [ ] Service
  - [ ] Ingress
 - [ ] Integration in Azure monitor for logging & monitoring
