### ISSUE TITLE
Advance ASA to Beta

### ISSUE THREAD

**Issue by rajeshkamal5050** [Azure/azure-dev#2499]
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-dev/pull/2500
- [ ] https://github.com/Azure/azure-dev/issues/2501
- [ ] https://github.com/Azure/azure-dev/issues/2503
```

**Comment by savannahostrowski** [comment]
I think this can be closed now as all PRs have been merged!
