### ISSUE TITLE
Support for pluggable Template sources

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-dev#2529]
Today the `azd template list` command displays a static list of available templates curated internally by the AZD team and controlled via a source controlled JSON file.

## Requirements
1. Ability to reference 1 or many external template sources
2. Template sources support JSON or YAML files

## Template Source Types
1. FileSystemTemplateSource - References a local file path
2. UriTemplateSource - Referenced an HTTP/HTTPS addressable URL
3. CustomTemplateSource - Custom implementation that returns list of externally managed templates (ADE)
```[tasklist]
### Tasks
- [ ] Design template source schema
- [ ] Implement FileSystemTemplateSource
- [ ] Implement UriTemplateSource
- [ ] Update `azd template list` command
- [ ] Design configuration schema for template sources
- [ ] Implement DevCenterTemplateSource
```
