### ISSUE TITLE
Investigate dev-ify story

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#253]
Azdev-ify journey
**Step 1 - Exploration/initialization**

- [x] Azdev-ify blog series (@puicchan)
      - https://aka.ms/azure-dev/azdevifyblog
      - https://aka.ms/azure-dev/azdevifyblog2
- [ ] Learn.microsoft.com Training modules for azdev-ify (based on Azdev-ify blog series)
- [ ] Explore CodeTour for azdev-ify (@puicchan)
- [x] I should not need to provide Azure specific information while still exploring. Related https://github.com/Azure/azure-dev/issues/112
- [ ] I want azd to scaffold files like GitHub/AzDo files for me. Related: #135 )  
 
**Step 2 - Set up IaC files**

- [ ] I want to be able to easily reuse Todo sample templates IaC files in Todo. Related: various simplification/reorg of /core; https://github.com/Azure/azure-dev/issues/751

**Step 3 - Tie everything together**

- [x] Document azure.yaml in Dev Hub (https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/azd-schema)
- [ ] Instrumenting my app should be easier; related: https://github.com/Azure/azure-dev/issues/355
- [ ] Make tasks.json/launch.json more generic for easy re-use: https://github.com/Azure/azure-dev/issues/1169

**Step 4 - Test and debug**

- [ ] I want to be able to run a command to validate Bicep and azd convention and know what I need to do next to fix my issue(s) (https://github.com/Azure/azure-dev/issues/1044)

**Step 5 - azd provision and deploy**

**Comment by savannahostrowski** [comment]
@puicchan Is this just moving to the next iteration? Or do you have another item you are using to track your work? Any updates?

**Comment by puicchan** [comment]
Yup. I've moved it.

**Comment by savannahostrowski** [comment]
Re. CodeTours, I have a prototype linked in #362 (for template orientation and an overview of IaC). Check it out.

**Comment by savannahostrowski** [comment]
Going to move this out of Germanium since it's an epic that will not get completed in full during that semester. 

We will pull in necessary sub issues though!

**Comment by puicchan** [comment]
Closing this in favor of composability.
