### ISSUE TITLE
[awesome-azd] UI Updates for Ignite

### ISSUE THREAD

**Issue by gkulin** [Azure/azure-dev#2865]
Priority order of awesome-azd items to be delivered by Ignite on November 14 (adding to November milestone for tracking purposes)

- [ ] 1. [P0] Filter top bar [Filter Bar · Issue #152](https://github.com/Azure/awesome-azd/issues/152)
- [ ] 2. [P0] Empty search page [Empty Search Result · Issue #191](https://github.com/Azure/awesome-azd/issues/191)
- [ ] 3. [P0] Card panel updates [Card Panel · Issue #150](https://github.com/Azure/awesome-azd/issues/150)
- [ ] 4. [P0] Update background, accent colors, icon colors on [Update About & Contribute pages](https://github.com/Azure/awesome-azd/issues/223)
- [ ] 5. [P0] FOUC (png is fixed but there are other improvements to be made) [Optimize assets · Issue #213](https://github.com/Azure/awesome-azd/issues/213)
- [ ] 6. [P1] Dark mode [Dark mode · Issue #216](https://github.com/Azure/awesome-azd/issues/216)
- [ ] 7. [P1] Add AI view [Add AI top-level filter · Issue #222](https://github.com/Azure/awesome-azd/issues/222)

**Comment by savannahostrowski** [comment]
We ideally want these updates finished by Universe (November 8-9th).
