### ISSUE TITLE
Enabling AI App Development

### ISSUE THREAD

**Issue by rajeshkamal5050** [Azure/azure-dev#3564]
- [ ] Enhance azd core or AVM modules for provisioning AI resources
- [x] Enhance deployment support for AI apps

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-dev/issues/3458
```

**Comment by wbreza** [comment]
Resolved with #3718 #3816
