### ISSUE TITLE
Azd tools/CLI Extension Framework

### ISSUE THREAD

**Issue by rajeshkamal5050** [Azure/azure-dev#3565]
Adds the ability for partner teams to build and ship official extensions for `azd`.

[Design Spec](https://microsoft.sharepoint.com/:fl:/s/1e32fb7a-ff2a-4c7d-ad2a-b046eef1247d/EU5Dya0gS7xGhKW7MqH32CQBYBvNPDJK1xb859Sr0Yx6hQ?e=gjZ2N0&nav=cz0lMkZzaXRlcyUyRjFlMzJmYjdhLWZmMmEtNGM3ZC1hZDJhLWIwNDZlZWYxMjQ3ZCZkPWIlMjFJSHBrNVhrem9rNk5CMGVUdFJmZ28tbG5DcGc2WXlsTGs5VjlQWWZ4RnliRmxLWG02dWpGU0pva3Rqak4yWmQ2JmY9MDFUTUlNWjNTT0lQRTIySUNMWFJESUpKTjNHS1E3UFdCRSZjPSUyRiZhPUxvb3BBcHAmcD0lNDBmbHVpZHglMkZsb29wLXBhZ2UtY29udGFpbmVyJng9JTdCJTIydyUyMiUzQSUyMlQwUlRVSHh0YVdOeWIzTnZablF1YzJoaGNtVndiMmx1ZEM1amIyMThZaUZKU0hCck5WaHJlbTlyTms1Q01HVlVkRkptWjI4dGJHNURjR2MyV1hsc1RHczVWamxRV1daNFJubGlSbXhMV0cwMmRXcEdVMHB2YTNScWFrNHlXbVEyZkRBeFZFMUpUVm96VVV3MVdFRk1VekpDTWtOR1FrdExSRFV6VjBsUldWaERNa1klM0QlMjIlMkMlMjJpJTIyJTNBJTIyNTcyYmMwODMtMzMwZi00YWE4LWJmYzgtODk1OGNhMTU1NWU1JTIyJTdE)

```[tasklist]
### Tasks
- [ ] Define requirements for official extensions
- [ ] Partner team extension signing process
```

```[tasklist]
### Related Issues
- [ ] https://github.com/Azure/azure-dev/issues/4388
- [ ] https://github.com/Azure/azure-dev/issues/4390
- [ ] https://github.com/Azure/azure-dev/issues/4389
- [ ] https://github.com/Azure/azure-dev/issues/4391
- [ ] https://github.com/Azure/azure-dev/issues/4392
```
