### ISSUE TITLE
UI implementation on AI site

### ISSUE THREAD

**Issue by hemarina** [Azure/azure-dev#3688]
Details of issues will be created in new AI repo
- [x] Nav Bar: https://github.com/Azure/ai-apps/issues/5
- [x] Cover Page – Cover + Featured AI templates: https://github.com/Azure/ai-apps/issues/6
- [x] Filter – tags+ View all templates: https://github.com/Azure/ai-apps/issues/7
- [x] Search bar + Sort by bar: https://github.com/Azure/ai-apps/issues/8
- [x] Card + gather data from github repository: https://github.com/Azure/ai-apps/issues/9
- [x] Card Panel: https://github.com/Azure/ai-apps/issues/11
- [x] Survey Card: https://github.com/Azure/ai-apps/issues/19
- [x] Empty Search Page: https://github.com/Azure/ai-apps/issues/18
- [ ] Remove docusaurus (not blocker, implement it before target date if we have time, perhaps using hugo): https://github.com/Azure/ai-apps/issues/12
