### ISSUE TITLE
Codespaces developer environments support

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-dev#370]

**Comment by savannahostrowski** [comment]
Can we outline more specifically what does and does not work in Codespaces today? Is it just that you can't login via Azure? That's the problem I ran into. Is this the only issue?

**Comment by jongio** [comment]
1. You have to run az login --use-device-code
2. You can't run or debug the application in codespace

@v-xuto - Can you please do a full test pass on Codespaces and file any issues discovered?  Thanks!

**Comment by v-xuto** [comment]
@jongio We have finished the manual tests in the `codespace` for the seven templates. 

Test results in `codespace` for seven templates:

- **todo-csharp-cosmos-sql :**
  New issue:  [issue#552](https://github.com/Azure/azure-dev/issues/552)
  Deployment is not valid according to the validation procedure in todo-nodejs-mongo-swa-func.

- **todo-nodejs-mongo-aca, todo-nodejs-mongo-swa-func, todo-python-mongo-swa-func, 
     todo-python-mongo, todo-nodejs-mongo, todo-python-mongo-aca:**
  Old issues: [issue#246](https://github.com/Azure/azure-dev/issues/246),  [issue#291](https://github.com/Azure/azure-dev/issues/291)

  When we directly use the templates to test, there is an old  [issue#246](https://github.com/Azure/azure-dev/issues/246).
  But [issue#246](https://github.com/Azure/azure-dev/issues/246) fixed by PR [#505](https://github.com/Azure/azure-dev/pull/505) .
  So, when we update the code in these templates by PR [#505](https://github.com/Azure/azure-dev/pull/505), we will can't reproduce the [issue#246](https://github.com/Azure/azure-dev/issues/246), and our test encountered the old [issue#291](https://github.com/Azure/azure-dev/issues/291).

  After investigating, the code in the `azure-dev` repo is out of sync with the code in other templates.

**Notes:** 
We will have an error when excute command `bash ./test-templates.sh -c false`: Host system is missing dependencies. 
To solve this issue, we can excute this command based on [comments](https://github.com/microsoft/playwright-python/issues/498#issuecomment-856349356):
```
sudo apt-get install -y gstreamer1.0-libav libnss3-tools libatk-bridge2.0-0 libcups2-dev libxkbcommon-x11-0 libxcomposite-dev libxrandr2 libgbm-dev libgtk-3-0
```

**Comment by danieljurek** [comment]
Goals: 

* [x] `azd` detects it's in codespaces and logs in with `--use-device-code`
* [ ] Foreach sample repo: codespaces scenarios work
    * [ ] La

Codespace scenario: 
1. Create new codespace from template repo (possibly fork)
2. In terminal: `curl -fsSL https://aka.ms/install-azd.sh | bash -s -- --version daily`
3. In vscode extension:
    1. azd provision
4. Debugger Launch API 
5. Debugger Launch Web

Repo List: 

* [ ] Azure-Samples/todo-nodejs-mongo-terraform 
* [ ] Azure-Samples/todo-nodejs-mongo           
* [ ] Azure-Samples/todo-csharp-cosmos-sql      
* [ ] Azure-Samples/todo-python-mongo-aca       
* [ ] Azure-Samples/todo-python-mongo-swa-func  
* [ ] Azure-Samples/todo-python-mongo-terraform 
* [ ] Azure-Samples/todo-python-mongo           
* [ ] Azure-Samples/todo-nodejs-mongo-aca       
* [ ] Azure-Samples/todo-nodejs-mongo-swa-func  
* [ ] Azure-Samples/todo-csharp-sql             

Notes: 
* Observed crash when running both API and Web simultaneously... Use a 4GB RAM instance instead of one with 2GB 
* The vscode plugin is installed in the codespaces environment by default but we still get a recommendation to install it
* Should we ensure that provision has been run on each launch? (what's the hang time for deploying if everything's already been deployed?)

**Comment by savannahostrowski** [comment]
Are we still investigating getting `azd` included in the Codespaces image? I think it'd be amazing if we could eliminate the install step - that's be the goal, IMO.

**Comment by danieljurek** [comment]
These are mostly notes to myself. I'm installing `daily` which is the latest of what's in `main` and hasn't yet been released. Once we do the release next week we can eliminate that step.

**Comment by savannahostrowski** [comment]
Sweet - thanks Daniel!

**Comment by danieljurek** [comment]
Further discussion with @philliphoff on Friday yielded a few more pieces of information. 

* dotenv tasks cannot presently "end" when a nested background task reaches an "end" ... this means that for frontend debugging we'll never launch the browser because the the `Web npm start` task never completes. 
* We can't launch a browser from codespaces inside the browser, this appears to be a limitation of vscode when running in the browser. 

To fix this we'd need to: 
* Implement a task which can run commands like the `Web npm start` task, but with a dotenv file (location dynamically determined). This task would need to use matchers so that it could pass control back to the task system.

**Comment by weikanglim** [comment]
@savannahostrowski With all the recent fixes by @danieljurek and myself, here's what works and doesn't work:

## Codespaces (Desktop and Web)

1 outstanding issue: https://github.com/Azure/azure-dev/issues/922 - Python debugging doesn't work. This happens on local `devcontainer` as well.

## Codespaces on Desktop

### Working:

- All `azd` commands.
- All debugging activities for Web.
- All debugging activities for API.

### Not working:

- None known at this point (except for the outstanding Python issue)

## Codespaces on Web

### Working:

- All `azd` commands.
- All debugging activities for API.

### Not working:
- Launching web with VSCode debugging does not work -- this is due to "VSCode in browser" limitation. It's a browser, and it's unable to launch another browser process with JS source map attached.
- Launching web without VSCode debugging. This currently requires the following manual-steps unless we address #918
   - Change API visibility to public (This exposes your developer-box instance on the public web)
   - Change the setting for web to point to the public API endpoint

Without VSCode debugging for front-end JS, the Codespaces in browser experience still feels like an incomplete experience.  Thus, I would rather not do #918 and tell users the story that:
- If you are doing development that doesn't require launching a web browser, go ahead with Codespaces in browser.
- Otherwise, we recommend Codespaces in Desktop will be a better development experience

There's also other considerations about supporting VSCode in browser that gives me pause:
- Less secure. The user needs to open up the codespace instance containing their development servers to be completely Public on the internet -- they wouldn't need to do this in the Desktop experience
- Cost of integration. We would have to introduce `codespace` specific integration points to configure the magic -- which we haven't done up to this point (except for the one-line device code detection in `azd`).

**Comment by savannahostrowski** [comment]
Also leaving a note here for the record. I think Codespaces is ready to announce in January (when we have our next big monthly release).  The issues noted here are not, IMO, azd issues but rather issues/limitations with Codespaces in the browser all up. See https://code.visualstudio.com/docs/remote/codespaces...notably, the limitations section where they denote that "Code running in a browser cannot launch another browser instance in debug mode for security reasons.". They encourage users to use Codespaces running locally in VS Code for that use case.

**Comment by savannahostrowski** [comment]
One last thing: the plan of record is still to include azd in the Codespaces image right? So that a user doesn't have to install the tool and things just work ™️  (e.g. I can fork a template, open in a Codespace and go right to right-click azure.yaml to run `azd up`)?

**Comment by jongio** [comment]
That works today.

**Comment by savannahostrowski** [comment]
Are you sure? I just tried it out and was still prompted to install azd (I got a toast notification) before azd up could run (and then subsequently prompted to install az, which is being remedied in another way)

**Comment by jongio** [comment]
Screenshots pls

**Comment by rajeshkamal5050** [comment]
Tried with,
**_- todo-java-mongo, seems to be working fine with no manual steps._**
<img width="1247" alt="codespaces-azd-todo-java-mongo" src="https://user-images.githubusercontent.com/11532743/200771015-9bc76e14-1437-4fb7-8af1-d9d5a98a65bf.png">
**_- todo-python-mongo and is not working. Azd seems to be installed. Looks like Az CLI has some installation issues._**
<img width="1248" alt="codespaces-azd-todo-python-mongo" src="https://user-images.githubusercontent.com/11532743/200771164-a1ed454a-eae7-46b9-bdf8-972957452b49.png">

**Comment by weikanglim** [comment]
> Are you sure? I just tried it out and was still prompted to install azd (I got a toast notification) before azd up could run (and then subsequently prompted to install az, which is being remedied in another way)

@savannahostrowski I think you're likely hitting this #165292. I believe VSCode has race conditions when initially launching the devcontainer in Codespaces. It's a false-positive prompt that is a bug in VSCode.

**Comment by savannahostrowski** [comment]
@weikanglim Ah yeah, I just tried again on another template and I didn't run into it again. Seems like I can `azd up` right from the get-go without install.

However, I did run into an interesting error. On `todo-python-mongo` I was able to fork the template and then open the Codespace. But when I just tried that same flow with `todo-python-mongo-aca`, I ran into this error on GitHub:
![image](https://user-images.githubusercontent.com/8949415/201779634-c60de4d4-80b9-45e1-9609-d7ca5b6b4541.png). 

I tried removing the description when I create the fork but this persists. It's likely a GitHub bug but not sure where that's coming from. I was able to just open a Codespace directly on the template to get around this.

**Comment by weikanglim** [comment]
@savannahostrowski That's odd. I was able to create a fork and open in Codespace.

If I needed to guess, that error is indeed from our GitHub repository's descriptions being over the validated length -- this either is a new requirement, or we had created this through our innersource Portal which may have bypassed the requirements.

The description on https://github.com/Azure-Samples/todo-python-mongo-aca is:
```
A complete ToDo application that includes everything you need to build, deploy, and monitor an Azure solution.
This application uses the Azure Developer CLI (azd) to get you up and running on Azure quickly, React.js for the Web application, Python (FastAPI) for the API, Azure Cosmos DB API for MongoDB for storage, and Azure Monitor for monitoring and logging.
```

Length = 361

I wonder if we can shorten the description to the thing that is different about this repository vs. others. The full description is still in the readme file.

```
A complete ToDo application that includes everything you need to build, deploy, and monitor an Azure solution.
This application uses the Azure Developer CLI (azd) to get you up and running on Azure quickly, Python (FastAPI) for the API on Azure Container Apps, Azure Cosmos DB API for MongoDB for storage.
```

**Comment by savannahostrowski** [comment]
Filed a bug on template description: https://github.com/Azure/azure-dev/issues/1199

This is ready for announcing in January. I've tagged with newsworthy.

**Comment by danieljurek** [comment]
This can be closed. New issue to document login behavior changes: https://github.com/Azure/azure-dev/issues/1216
