### ISSUE TITLE
Template Discoverability + Contribution

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#418]
- [ ] https://github.com/Azure/azure-dev/issues/398
- [ ] https://github.com/Azure/azure-dev/issues/287
- [ ] https://github.com/Azure/azure-dev/issues/425

**Comment by rajeshkamal5050** [comment]
@savannahostrowski closing since samples are now published to the Microsoft samples browser.
