### ISSUE TITLE
azd roadmap for Selenium semester [Se]

### ISSUE THREAD

**Issue by kristenwomack** [Azure/azure-dev#4378]
- [x] initial draft of semester roadmap
- [x] add advocacy planned events
- [x] composability updates after round of demo and feedback
- [x] mid-semester revisions
