### ISSUE TITLE
Extension command group

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-dev#4388]
Create a new `extension` command group within `azd` to manage the installation of available extensions.

```[tasklist]
### Tasks
- [ ] `azd extension list`
- [ ] `azd extension show`
- [ ] `azd extension install <extension-name>`
- [ ] `azd extension uninstall <extension-name>`
- [ ] `azd extension upgrade <extension-name>`
```
