### ISSUE TITLE
Extension registry

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-dev#4389]
Design and implement `azd` extension registry.
```[tasklist]
### Tasks
- [x] Storage location for registry (same storage account used for releases?)
- [x] Schema for registry
- [ ] Registry security and establishing trust
- [x] aka.ms links
- [ ] Include public key with `azd` binary to validate digital signatures
- [ ] https://github.com/Azure/azure-dev/issues/4388
```

**Comment by wbreza** [comment]
Initial registry is stored in github repo @ https://github.com/Azure/azure-dev/blob/main/cli/azd/extensions/registry.json
Registry schema is available @ https://github.com/Azure/azure-dev/blob/main/cli/azd/extensions/registry.schema.json

Registry is fronted by aka.ms link @ https://aka.ms/azd/extensions/registry

Initial set of `azd` extensions will be stored within the same storage account as `azd` core releases.
