### ISSUE TITLE
Extension Go Module SDK

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-dev#4392]
Build new Go module SDK that can be leveraged by extension developers.
```[tasklist]
### Tasks
- [x] Define release strategy
- [x] Define versioning strategy
- [x] Ability to load current `azd` project config
- [x] Ability to load current `azd` environment config and variables
- [x] Ability to load current `azd` machine/user config
- [x] Ability to prompt users to select an Azure resource of specified type
```

**Comment by wbreza** [comment]
Azd extensions will follow a semver style release strategy.
New versions will be appended to the extension within the registry
Extensions can release out of band from azd core.

See #4389 for details on registry.
