### ISSUE TITLE
UX Explorations: P0 Azd Extension Tree Code Proposal

### ISSUE THREAD

**Issue by rajeshkamal5050** [Azure/azure-dev#594]
### Issue Details

Review the `azd` VSCode extension tree view proposal and audit the P0 demo. Design to provide UX feedback and improvement concepts.

### Related Links
- [Tree Diagram Proposal](https://microsoft-my.sharepoint.com/:w:/p/karolz/Ec-lwWrN6c9JhkttGWITDngB7nVC7FvIXogGW9olNZDgIw?e=hCpwWu)
- [Austin's Notes + Questions](https://microsoft-my.sharepoint.com/:w:/p/austinauth/EawReZIeIcZImaGzMr3hTpIBE_Jx4PfmgDCPn4xhnzvngA?e=zC7ZLC)
- [Experience Audit of the P0 proposal](https://www.figma.com/file/6uKvpmw36uXaxp0dmoR5jw/Azd-Extension-P0-Tree-View---Experience-Audit?node-id=1%3A156)

### Task List
- [x] Review VS Code (learn how extensions work in VS Code)
- [x] Document initial questions
- [x] Review the proposal and document additional questions
- [x] Try existing extension commands
- [x] Share question doc for feedback from @savannahostrowski 
- [x] Discuss next steps with @savannahostrowski 
- [x] Schedule time with @savannahostrowski to run through demo scenarios
- [ ] Capture findings and feedback from demo scenarios, provide feedback to Phillip
- [ ] Create design recommendations based on findings

**Comment by Austinauth** [comment]
**Update 09/22/2022**
- Learned how extensions work in VS Code
- Captured initial Questions
- @savannahostrowski can you add details to the [questions doc](https://microsoft-my.sharepoint.com/:w:/p/austinauth/EawReZIeIcZImaGzMr3hTpIBE_Jx4PfmgDCPn4xhnzvngA?e=f0PXVU) where you're tagged before I'm back on Oct 10th?

**Comment by Austinauth** [comment]
**Update 10/09/2022**
- Had sync with Savannah
- Updated task list
- Next steps: Complete tasks above by end of week

**Comment by Austinauth** [comment]
** Update 10/17/2022**
This update covers the work completed last week.

- Prototype extension successfully installed but did not have a chance to ideate on improvements yet
- Scope of design work needed is likely less than initially suspected
- **This week:** I will do a mini audit on the functionality (much smaller than the Awesome AZD audit)
- **This week:** I will explore minor UX tweaks like: Icon usage, Color No Service, and Error Messaging
- **This week:** (From @savannahostrowski) Document use cases step-by-step so that we can walk through them and audit in a more targeted way.

**Comment by Austinauth** [comment]
**Update 10/25/2022**
- Attempted to audit a few of the scenarios Savannah identified. I was not able to complete most of the scenarios due to the extension still being in an unstable state as it is being developed.
- @savannahostrowski and I will run through the extension together once it is in a more stable state. 
- Until then I'm putting this task on hold.

**Comment by Austinauth** [comment]
**Update 11/07/2022**

- Have not had the extra time to dedicate to this effort
- **This week:** Will reach out to Phillip this week/next week regarding status of the extension
- **This week:** Meeting with other designers working on VS Code extensions to better understand design rules & patterns
