### ISSUE TITLE
Azure Developer CLI Golden Path (install ➡️ local development ➡️ first deployment)

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#874]
As part of an effort to make `azd` onboarding awesome, this issue aims to track various stages of the onboarding experience (let's call it the golden path; install ➡️ local development ➡️ first deployment) that might cause application developers issues and/or slow their progress getting their app to the cloud using `azd`.

Right now, I've grouped these issues into a couple different categories:
- Installation of `azd` + CLI/template dependencies
- Familiarization with `azd` commands/capabilities
- Make project initialization delightful
- Templates
- CLI Outputs

Each category has at least one JTBD/user story associated with it. This list of issues is dynamic so if there are other things (or categories) that you think are pain points/unnecessary friction to getting started with `azd`, let me know and we can figure out the best way to get it incorporated! All issues linked here have the `golden-path` tag on them.

# A. Installation of `azd` + CLI/template dependencies
1. _"As an application developer, I want to install the Azure Developer CLI with my package manager of choice and with minimal required  dependencies, so that I can get started without having to jump around between documentation and encounter minimal dependency issues"_
- [x] https://github.com/Azure/azure-dev/issues/709
- [x] https://github.com/Azure/azure-dev/issues/821
- [ ] https://github.com/Azure/azure-dev/issues/847

# B. Familiarization with `azd` commands/capabilities
1. _"As an application developer, I need to be able to easily familiarize myself with Azure Developer CLI capabilities after I install the tool, so that I can meaningfully use the CLI and complete my task at hand (e.g. getting my application deployed on Azure)"_
- [ ] https://github.com/Azure/azure-dev/issues/822

# C. Make project initialization delightful
1. _"As an application developer, I want the Azure Developer CLI to provide me with an opinionated take on what cloud infrastructure I need to get my application up to the cloud, with minimal overhead, so that I don't have to do a ton of research and my productivity isn't hindered."_
- [ ] https://github.com/Azure/azure-dev/issues/705
- [x] https://github.com/Azure/azure-dev/issues/819
- [ ] https://github.com/Azure/azure-dev/issues/808
	- [ ] https://github.com/Azure/azure-dev/issues/112
	- [ ] https://github.com/Azure/azure-dev/issues/335
- [ ] https://github.com/Azure/azure-dev/issues/1391

# D. Templates
1. _"As a an application developer, I want to be able to easily find a template that matches my application stack, so that I can quickly get started on Azure and be set up for success from day 1"_
1. "_As an application developer, I want to know that a template I choose with work with the latest version of the Azure Developer CLI, so that I know that I am setting my application up with best practices and securely on Azure"_
- [ ] https://github.com/Azure/azure-dev/issues/418
	- [ ] https://github.com/Azure/azure-dev/issues/425
	- [x] https://github.com/Azure/azure-dev/issues/287
- [x] https://github.com/Azure/azure-dev/issues/637
- [x] https://github.com/Azure/azure-dev/issues/273

# E. CLI outputs
1. _"As an application developer, I need to be able to recover from errors that I encounter when using the Azure Developer CLI, so that I can get my application's infrastructure provision and my app deployed on Azure"_
1. _"As an application developer, I need to be able to clearly understand what is being provisioned/deployed for me on Azure, so that I can the cloud components of my application, understand how my application is mapped out in the Azure Portal + learn the fundamentals_
- [x] https://github.com/Azure/azure-dev/issues/243
- [x] https://github.com/Azure/azure-dev/issues/255
- [x] https://github.com/Azure/azure-dev/issues/508
